spring:
  # 데이터베이스 설정
  datasource:
    url: jdbc:mysql://localhost:3306/snaplink?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: update # 개발 환경에서는 자동 스키마 업데이트
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  # Redis 설정
  redis:
    host: localhost
    port: 6379
    timeout: 3000

# 로깅 설정
logging:
  level:
    root: INFO
    org.springframework: INFO
    org.hibernate: INFO
    org.hibernate.SQL: DEBUG # SQL 쿼리 로깅
    org.hibernate.type.descriptor.sql: TRACE # SQL 파라미터 로깅
    com.yourcompany.snaplink: DEBUG # 애플리케이션 패키지 로깅 레벨 (실제 패키지명으로 수정 필요)

# 애플리케이션 설정
app:
  shorturl:
    domain: http://localhost:8080