spring:
  profiles:
    active: dev
  config:
    import:
      - optional:file:config/application-secrets.yml
  datasource:
    hikari:
      # HikariCP 튜닝 전
#      maximum-pool-size: 10
#      connection-timeout: 30000
      # HikariCP 튜닝 후
      maximum-pool-size: 20              # 동시 연결 수 증가
      minimum-idle: 5                    # 최소 유지 연결 수
      idle-timeout: 300000               # 유휴 연결 제거 시간 (5분)
      max-lifetime: 1800000              # 최대 수명 (30분)
      connection-timeout: 20000          # 연결 타임아웃 (20초)
      connection-test-query: SELECT 1    # 연결 유효성 검사 쿼리
      pool-name: SnapLinkHikariPool      # 커넥션 풀 이름 (모니터링용)
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,caches
  endpoint:
    health:
      show-details: when_authorized
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http.server.requests: true
        url.redirect.time: true
      percentiles:
        http.server.requests: 0.5, 0.95, 0.99
        url.redirect.time: 0.5, 0.95, 0.99
  info:
    git:
      mode: full

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8

  api-docs:
    enabled: true  # API 문서(`/v3/api-docs`) 활성화 여부 (기본값: true)
    path: /v3/api-docs  # API 문서의 엔드포인트 변경 (기본값: /v3/api-docs)
    groups.enabled: true  # 여러 개의 API 그룹을 지원할지 여부

  swagger-ui:
    enabled: true  # Swagger UI 활성화 여부 (기본값: true)
    path: /swagger-ui.html  # Swagger UI 접속 경로 변경 (기본값: /swagger-ui.html)
    operationsSorter: method  # API 정렬 기준 (alpha: 알파벳순, method: HTTP 메서드 순)
    tagsSorter: alpha  # 태그 정렬 방식 (alpha: 알파벳순 정렬)
    display-request-duration: true  # 요청 실행 시간 표시 여부
    doc-expansion: none  # Swagger UI에서 API 설명의 기본 펼침 상태 (none: 닫힘, list: 펼침, full: 전체 펼침)
    persistAuthorization: true  # 페이지 새로고침 후에도 Authorization 헤더 유지 여부
    defaultModelsExpandDepth: -1  # 모델 스키마의 기본 펼침 깊이 (-1이면 모델 펼쳐지지 않음)

  paths-to-match:  # OpenAPI 문서에서 포함할 엔드포인트 패턴
    - /api/**  # /api로 시작하는 모든 경로 포함
  cache:
    disabled: true  # OpenAPI 문서의 캐싱 비활성화 (기본값: false)
  show-actuator: false  # Spring Actuator 엔드포인트를 Swagger UI에 표시할지 여부 (기본값: false)

app:
  version: @project.version@